version: "3.8"

services:
  database:
    image: "mysql:8.4-oraclelinux9"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - express-2fa-data:/var/lib/mysql
    env_file:
      - ./env/database.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    ports:
      - "80:80"   
    depends_on:
      - database 

volumes:
  express-2fa-data: